// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package proto

import (
	"fmt"
)

// ActivityFrame represents a single heartbeat from the desktop agent.
type ActivityFrame struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty" bson:"uuid"`
	DeviceId    string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty" bson:"device_id"`
	AppName     string `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty" bson:"app_name"`
	WindowTitle string `protobuf:"bytes,4,opt,name=window_title,json=windowTitle,proto3" json:"window_title,omitempty" bson:"window_title"`
	StartTime   int64  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" bson:"start_time"`
	DurationMs  int64  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty" bson:"duration_ms"`
	IsIdle      bool   `protobuf:"varint,7,opt,name=is_idle,json=isIdle,proto3" json:"is_idle,omitempty" bson:"is_idle"`
}

func (x *ActivityFrame) GetUuid() string        { return x.Uuid }
func (x *ActivityFrame) GetDeviceId() string     { return x.DeviceId }
func (x *ActivityFrame) GetAppName() string      { return x.AppName }
func (x *ActivityFrame) GetWindowTitle() string  { return x.WindowTitle }
func (x *ActivityFrame) GetStartTime() int64     { return x.StartTime }
func (x *ActivityFrame) GetDurationMs() int64    { return x.DurationMs }
func (x *ActivityFrame) GetIsIdle() bool         { return x.IsIdle }
func (x *ActivityFrame) String() string          { return fmt.Sprintf("%+v", *x) }
func (x *ActivityFrame) ProtoMessage()           {}
func (x *ActivityFrame) Reset()                  { *x = ActivityFrame{} }

// SyncResponse is the ack sent back to the agent after processing a frame.
type SyncResponse struct {
	LastProcessedUuid string `protobuf:"bytes,1,opt,name=last_processed_uuid,json=lastProcessedUuid,proto3" json:"last_processed_uuid,omitempty"`
	Success           bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SyncResponse) GetLastProcessedUuid() string { return x.LastProcessedUuid }
func (x *SyncResponse) GetSuccess() bool              { return x.Success }
func (x *SyncResponse) String() string                { return fmt.Sprintf("%+v", *x) }
func (x *SyncResponse) ProtoMessage()                 {}
func (x *SyncResponse) Reset()                        { *x = SyncResponse{} }

// PairingRequest is sent by the agent to initiate or check device pairing.
type PairingRequest struct {
	HardwareId string `protobuf:"bytes,1,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
}

func (x *PairingRequest) GetHardwareId() string { return x.HardwareId }
func (x *PairingRequest) String() string        { return fmt.Sprintf("%+v", *x) }
func (x *PairingRequest) ProtoMessage()         {}
func (x *PairingRequest) Reset()                { *x = PairingRequest{} }

// PairingResponse returns the user-facing code to enter on the web dashboard.
type PairingResponse struct {
	UserCode  string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	ExpiresIn int32  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
}

func (x *PairingResponse) GetUserCode() string { return x.UserCode }
func (x *PairingResponse) GetExpiresIn() int32 { return x.ExpiresIn }
func (x *PairingResponse) String() string      { return fmt.Sprintf("%+v", *x) }
func (x *PairingResponse) ProtoMessage()       {}
func (x *PairingResponse) Reset()              { *x = PairingResponse{} }

// TokenResponse returns the permanent API key after successful pairing.
type TokenResponse struct {
	Authenticated bool   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *TokenResponse) GetAuthenticated() bool { return x.Authenticated }
func (x *TokenResponse) GetApiKey() string      { return x.ApiKey }
func (x *TokenResponse) String() string         { return fmt.Sprintf("%+v", *x) }
func (x *TokenResponse) ProtoMessage()          {}
func (x *TokenResponse) Reset()                 { *x = TokenResponse{} }
