// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: activity.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// Telemetry Service
// ---------------------------------------------------------------------------

// TelemetryServer is the server API for the Telemetry service.
type TelemetryServer interface {
	StreamLogs(Telemetry_StreamLogsServer) error
}

// UnimplementedTelemetryServer should be embedded to forward-compat new RPCs.
type UnimplementedTelemetryServer struct{}

func (UnimplementedTelemetryServer) StreamLogs(Telemetry_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}

// Telemetry_StreamLogsServer is the server-side streaming interface.
type Telemetry_StreamLogsServer interface {
	Send(*SyncResponse) error
	Recv() (*ActivityFrame, error)
	grpc.ServerStream
}

type telemetryStreamLogsServer struct {
	grpc.ServerStream
}

func (x *telemetryStreamLogsServer) Send(m *SyncResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryStreamLogsServer) Recv() (*ActivityFrame, error) {
	m := new(ActivityFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Telemetry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activity.Telemetry",
	HandlerType: (*TelemetryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Telemetry_StreamLogs_Handler,
			ServerStreams:  true,
			ClientStreams:  true,
		},
	},
	Metadata: "activity.proto",
}

func _Telemetry_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServer).StreamLogs(&telemetryStreamLogsServer{stream})
}

func RegisterTelemetryServer(s *grpc.Server, srv TelemetryServer) {
	s.RegisterService(&_Telemetry_serviceDesc, srv)
}

// ---------------------------------------------------------------------------
// AuthService
// ---------------------------------------------------------------------------

// AuthServiceServer is the server API for the AuthService.
type AuthServiceServer interface {
	InitiatePairing(context.Context, *PairingRequest) (*PairingResponse, error)
	CheckPairingStatus(context.Context, *PairingRequest) (*TokenResponse, error)
}

// UnimplementedAuthServiceServer should be embedded to forward-compat new RPCs.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) InitiatePairing(context.Context, *PairingRequest) (*PairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePairing not implemented")
}

func (UnimplementedAuthServiceServer) CheckPairingStatus(context.Context, *PairingRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPairingStatus not implemented")
}

func _AuthService_InitiatePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InitiatePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.AuthService/InitiatePairing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InitiatePairing(ctx, req.(*PairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckPairingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckPairingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.AuthService/CheckPairingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckPairingStatus(ctx, req.(*PairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activity.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiatePairing",
			Handler:    _AuthService_InitiatePairing_Handler,
		},
		{
			MethodName: "CheckPairingStatus",
			Handler:    _AuthService_CheckPairingStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}
